// Generated by scripts/process-team-diaries.mjs. Do not edit by hand.
import type { StaticImageData } from "next/image";

import teamDiaryAsset01Full from "@/assets/team-diaries/day-01/day-01-01.webp";
import teamDiaryAsset01Thumbnail from "@/assets/team-diaries/day-01/day-01-01-thumb.webp";
import teamDiaryAsset02Full from "@/assets/team-diaries/day-01/day-01-02.webp";
import teamDiaryAsset02Thumbnail from "@/assets/team-diaries/day-01/day-01-02-thumb.webp";
import teamDiaryAsset03Full from "@/assets/team-diaries/day-01/day-01-03.webp";
import teamDiaryAsset03Thumbnail from "@/assets/team-diaries/day-01/day-01-03-thumb.webp";
import teamDiaryAsset04Full from "@/assets/team-diaries/day-01/day-01-04.webp";
import teamDiaryAsset04Thumbnail from "@/assets/team-diaries/day-01/day-01-04-thumb.webp";
import teamDiaryAsset05Full from "@/assets/team-diaries/day-01/day-01-05.webp";
import teamDiaryAsset05Thumbnail from "@/assets/team-diaries/day-01/day-01-05-thumb.webp";
import teamDiaryAsset06Full from "@/assets/team-diaries/day-01/day-01-06.webp";
import teamDiaryAsset06Thumbnail from "@/assets/team-diaries/day-01/day-01-06-thumb.webp";
import teamDiaryAsset07Full from "@/assets/team-diaries/day-01/day-01-07.webp";
import teamDiaryAsset07Thumbnail from "@/assets/team-diaries/day-01/day-01-07-thumb.webp";
import teamDiaryAsset08Full from "@/assets/team-diaries/day-01/day-01-08.webp";
import teamDiaryAsset08Thumbnail from "@/assets/team-diaries/day-01/day-01-08-thumb.webp";
import teamDiaryAsset09Full from "@/assets/team-diaries/day-01/day-01-09.webp";
import teamDiaryAsset09Thumbnail from "@/assets/team-diaries/day-01/day-01-09-thumb.webp";
import teamDiaryAsset10Full from "@/assets/team-diaries/day-02/day-02-01.webp";
import teamDiaryAsset10Thumbnail from "@/assets/team-diaries/day-02/day-02-01-thumb.webp";
import teamDiaryAsset11Full from "@/assets/team-diaries/day-02/day-02-02.webp";
import teamDiaryAsset11Thumbnail from "@/assets/team-diaries/day-02/day-02-02-thumb.webp";
import teamDiaryAsset12Full from "@/assets/team-diaries/day-02/day-02-03.webp";
import teamDiaryAsset12Thumbnail from "@/assets/team-diaries/day-02/day-02-03-thumb.webp";
import teamDiaryAsset13Full from "@/assets/team-diaries/day-02/day-02-04.webp";
import teamDiaryAsset13Thumbnail from "@/assets/team-diaries/day-02/day-02-04-thumb.webp";
import teamDiaryAsset14Full from "@/assets/team-diaries/day-02/day-02-05.webp";
import teamDiaryAsset14Thumbnail from "@/assets/team-diaries/day-02/day-02-05-thumb.webp";
import teamDiaryAsset15Full from "@/assets/team-diaries/day-02/day-02-06.webp";
import teamDiaryAsset15Thumbnail from "@/assets/team-diaries/day-02/day-02-06-thumb.webp";
import teamDiaryAsset16Full from "@/assets/team-diaries/day-02/day-02-07.webp";
import teamDiaryAsset16Thumbnail from "@/assets/team-diaries/day-02/day-02-07-thumb.webp";
import teamDiaryAsset17Full from "@/assets/team-diaries/day-02/day-02-08.webp";
import teamDiaryAsset17Thumbnail from "@/assets/team-diaries/day-02/day-02-08-thumb.webp";
import teamDiaryAsset18Full from "@/assets/team-diaries/day-03/day-03-01.webp";
import teamDiaryAsset18Thumbnail from "@/assets/team-diaries/day-03/day-03-01-thumb.webp";
import teamDiaryAsset19Full from "@/assets/team-diaries/day-03/day-03-02.webp";
import teamDiaryAsset19Thumbnail from "@/assets/team-diaries/day-03/day-03-02-thumb.webp";
import teamDiaryAsset20Full from "@/assets/team-diaries/day-03/day-03-03.webp";
import teamDiaryAsset20Thumbnail from "@/assets/team-diaries/day-03/day-03-03-thumb.webp";
import teamDiaryAsset21Full from "@/assets/team-diaries/day-03/day-03-04.webp";
import teamDiaryAsset21Thumbnail from "@/assets/team-diaries/day-03/day-03-04-thumb.webp";
import teamDiaryAsset22Full from "@/assets/team-diaries/day-03/day-03-05.webp";
import teamDiaryAsset22Thumbnail from "@/assets/team-diaries/day-03/day-03-05-thumb.webp";
import teamDiaryAsset23Full from "@/assets/team-diaries/day-03/day-03-06.webp";
import teamDiaryAsset23Thumbnail from "@/assets/team-diaries/day-03/day-03-06-thumb.webp";
import teamDiaryAsset24Full from "@/assets/team-diaries/day-03/day-03-07.webp";
import teamDiaryAsset24Thumbnail from "@/assets/team-diaries/day-03/day-03-07-thumb.webp";
import teamDiaryAsset25Full from "@/assets/team-diaries/day-03/day-03-08.webp";
import teamDiaryAsset25Thumbnail from "@/assets/team-diaries/day-03/day-03-08-thumb.webp";
import teamDiaryAsset26Full from "@/assets/team-diaries/day-03/day-03-09.webp";
import teamDiaryAsset26Thumbnail from "@/assets/team-diaries/day-03/day-03-09-thumb.webp";
import teamDiaryAsset27Full from "@/assets/team-diaries/day-03/day-03-10.webp";
import teamDiaryAsset27Thumbnail from "@/assets/team-diaries/day-03/day-03-10-thumb.webp";
import teamDiaryAsset28Full from "@/assets/team-diaries/day-04/day-04-01.webp";
import teamDiaryAsset28Thumbnail from "@/assets/team-diaries/day-04/day-04-01-thumb.webp";
import teamDiaryAsset29Full from "@/assets/team-diaries/day-04/day-04-02.webp";
import teamDiaryAsset29Thumbnail from "@/assets/team-diaries/day-04/day-04-02-thumb.webp";
import teamDiaryAsset30Full from "@/assets/team-diaries/day-04/day-04-03.webp";
import teamDiaryAsset30Thumbnail from "@/assets/team-diaries/day-04/day-04-03-thumb.webp";
import teamDiaryAsset31Full from "@/assets/team-diaries/day-04/day-04-04.webp";
import teamDiaryAsset31Thumbnail from "@/assets/team-diaries/day-04/day-04-04-thumb.webp";
import teamDiaryAsset32Full from "@/assets/team-diaries/day-04/day-04-05.webp";
import teamDiaryAsset32Thumbnail from "@/assets/team-diaries/day-04/day-04-05-thumb.webp";
import teamDiaryAsset33Full from "@/assets/team-diaries/day-04/day-04-06.webp";
import teamDiaryAsset33Thumbnail from "@/assets/team-diaries/day-04/day-04-06-thumb.webp";
import teamDiaryAsset34Full from "@/assets/team-diaries/day-04/day-04-07.webp";
import teamDiaryAsset34Thumbnail from "@/assets/team-diaries/day-04/day-04-07-thumb.webp";
import teamDiaryAsset35Full from "@/assets/team-diaries/day-04/day-04-08.webp";
import teamDiaryAsset35Thumbnail from "@/assets/team-diaries/day-04/day-04-08-thumb.webp";
import teamDiaryAsset36Full from "@/assets/team-diaries/day-04/day-04-09.webp";
import teamDiaryAsset36Thumbnail from "@/assets/team-diaries/day-04/day-04-09-thumb.webp";
import teamDiaryAsset37Full from "@/assets/team-diaries/day-05/day-05-01.webp";
import teamDiaryAsset37Thumbnail from "@/assets/team-diaries/day-05/day-05-01-thumb.webp";
import teamDiaryAsset38Full from "@/assets/team-diaries/day-05/day-05-02.webp";
import teamDiaryAsset38Thumbnail from "@/assets/team-diaries/day-05/day-05-02-thumb.webp";
import teamDiaryAsset39Full from "@/assets/team-diaries/day-05/day-05-03.webp";
import teamDiaryAsset39Thumbnail from "@/assets/team-diaries/day-05/day-05-03-thumb.webp";
import teamDiaryAsset40Full from "@/assets/team-diaries/day-05/day-05-04.webp";
import teamDiaryAsset40Thumbnail from "@/assets/team-diaries/day-05/day-05-04-thumb.webp";
import teamDiaryAsset41Full from "@/assets/team-diaries/day-05/day-05-05.webp";
import teamDiaryAsset41Thumbnail from "@/assets/team-diaries/day-05/day-05-05-thumb.webp";
import teamDiaryAsset42Full from "@/assets/team-diaries/day-05/day-05-06.webp";
import teamDiaryAsset42Thumbnail from "@/assets/team-diaries/day-05/day-05-06-thumb.webp";
import teamDiaryAsset43Full from "@/assets/team-diaries/day-05/day-05-07.webp";
import teamDiaryAsset43Thumbnail from "@/assets/team-diaries/day-05/day-05-07-thumb.webp";
import teamDiaryAsset44Full from "@/assets/team-diaries/day-05/day-05-08.webp";
import teamDiaryAsset44Thumbnail from "@/assets/team-diaries/day-05/day-05-08-thumb.webp";
import teamDiaryAsset45Full from "@/assets/team-diaries/day-05/day-05-09.webp";
import teamDiaryAsset45Thumbnail from "@/assets/team-diaries/day-05/day-05-09-thumb.webp";
import teamDiaryAsset46Full from "@/assets/team-diaries/day-05/day-05-10.webp";
import teamDiaryAsset46Thumbnail from "@/assets/team-diaries/day-05/day-05-10-thumb.webp";
import teamDiaryAsset47Full from "@/assets/team-diaries/day-05/day-05-11.webp";
import teamDiaryAsset47Thumbnail from "@/assets/team-diaries/day-05/day-05-11-thumb.webp";
import teamDiaryAsset48Full from "@/assets/team-diaries/day-06/day-06-01.webp";
import teamDiaryAsset48Thumbnail from "@/assets/team-diaries/day-06/day-06-01-thumb.webp";
import teamDiaryAsset49Full from "@/assets/team-diaries/day-06/day-06-02.webp";
import teamDiaryAsset49Thumbnail from "@/assets/team-diaries/day-06/day-06-02-thumb.webp";
import teamDiaryAsset50Full from "@/assets/team-diaries/day-06/day-06-03.webp";
import teamDiaryAsset50Thumbnail from "@/assets/team-diaries/day-06/day-06-03-thumb.webp";
import teamDiaryAsset51Full from "@/assets/team-diaries/day-06/day-06-04.webp";
import teamDiaryAsset51Thumbnail from "@/assets/team-diaries/day-06/day-06-04-thumb.webp";
import teamDiaryAsset52Full from "@/assets/team-diaries/day-06/day-06-05.webp";
import teamDiaryAsset52Thumbnail from "@/assets/team-diaries/day-06/day-06-05-thumb.webp";
import teamDiaryAsset53Full from "@/assets/team-diaries/day-06/day-06-06.webp";
import teamDiaryAsset53Thumbnail from "@/assets/team-diaries/day-06/day-06-06-thumb.webp";
import teamDiaryAsset54Full from "@/assets/team-diaries/day-06/day-06-07.webp";
import teamDiaryAsset54Thumbnail from "@/assets/team-diaries/day-06/day-06-07-thumb.webp";
import teamDiaryAsset55Full from "@/assets/team-diaries/day-06/day-06-08.webp";
import teamDiaryAsset55Thumbnail from "@/assets/team-diaries/day-06/day-06-08-thumb.webp";
import teamDiaryAsset56Full from "@/assets/team-diaries/day-07/day-07-01.webp";
import teamDiaryAsset56Thumbnail from "@/assets/team-diaries/day-07/day-07-01-thumb.webp";
import teamDiaryAsset57Full from "@/assets/team-diaries/day-07/day-07-02.webp";
import teamDiaryAsset57Thumbnail from "@/assets/team-diaries/day-07/day-07-02-thumb.webp";
import teamDiaryAsset58Full from "@/assets/team-diaries/day-07/day-07-03.webp";
import teamDiaryAsset58Thumbnail from "@/assets/team-diaries/day-07/day-07-03-thumb.webp";
import teamDiaryAsset59Full from "@/assets/team-diaries/day-07/day-07-04.webp";
import teamDiaryAsset59Thumbnail from "@/assets/team-diaries/day-07/day-07-04-thumb.webp";
import teamDiaryAsset60Full from "@/assets/team-diaries/day-07/day-07-05.webp";
import teamDiaryAsset60Thumbnail from "@/assets/team-diaries/day-07/day-07-05-thumb.webp";
import teamDiaryAsset61Full from "@/assets/team-diaries/day-07/day-07-06.webp";
import teamDiaryAsset61Thumbnail from "@/assets/team-diaries/day-07/day-07-06-thumb.webp";
import teamDiaryAsset62Full from "@/assets/team-diaries/day-07/day-07-07.webp";
import teamDiaryAsset62Thumbnail from "@/assets/team-diaries/day-07/day-07-07-thumb.webp";
import teamDiaryAsset63Full from "@/assets/team-diaries/day-08/day-08-01.webp";
import teamDiaryAsset63Thumbnail from "@/assets/team-diaries/day-08/day-08-01-thumb.webp";
import teamDiaryAsset64Full from "@/assets/team-diaries/day-08/day-08-02.webp";
import teamDiaryAsset64Thumbnail from "@/assets/team-diaries/day-08/day-08-02-thumb.webp";
import teamDiaryAsset65Full from "@/assets/team-diaries/day-08/day-08-03.webp";
import teamDiaryAsset65Thumbnail from "@/assets/team-diaries/day-08/day-08-03-thumb.webp";
import teamDiaryAsset66Full from "@/assets/team-diaries/day-08/day-08-04.webp";
import teamDiaryAsset66Thumbnail from "@/assets/team-diaries/day-08/day-08-04-thumb.webp";
import teamDiaryAsset67Full from "@/assets/team-diaries/day-08/day-08-05.webp";
import teamDiaryAsset67Thumbnail from "@/assets/team-diaries/day-08/day-08-05-thumb.webp";
import teamDiaryAsset68Full from "@/assets/team-diaries/day-08/day-08-06.webp";
import teamDiaryAsset68Thumbnail from "@/assets/team-diaries/day-08/day-08-06-thumb.webp";
import teamDiaryAsset69Full from "@/assets/team-diaries/day-08/day-08-07.webp";
import teamDiaryAsset69Thumbnail from "@/assets/team-diaries/day-08/day-08-07-thumb.webp";
import teamDiaryAsset70Full from "@/assets/team-diaries/day-08/day-08-08.webp";
import teamDiaryAsset70Thumbnail from "@/assets/team-diaries/day-08/day-08-08-thumb.webp";

export type TeamDiaryImageId = "day-01-01" | "day-01-02" | "day-01-03" | "day-01-04" | "day-01-05" | "day-01-06" | "day-01-07" | "day-01-08" | "day-01-09" | "day-02-01" | "day-02-02" | "day-02-03" | "day-02-04" | "day-02-05" | "day-02-06" | "day-02-07" | "day-02-08" | "day-03-01" | "day-03-02" | "day-03-03" | "day-03-04" | "day-03-05" | "day-03-06" | "day-03-07" | "day-03-08" | "day-03-09" | "day-03-10" | "day-04-01" | "day-04-02" | "day-04-03" | "day-04-04" | "day-04-05" | "day-04-06" | "day-04-07" | "day-04-08" | "day-04-09" | "day-05-01" | "day-05-02" | "day-05-03" | "day-05-04" | "day-05-05" | "day-05-06" | "day-05-07" | "day-05-08" | "day-05-09" | "day-05-10" | "day-05-11" | "day-06-01" | "day-06-02" | "day-06-03" | "day-06-04" | "day-06-05" | "day-06-06" | "day-06-07" | "day-06-08" | "day-07-01" | "day-07-02" | "day-07-03" | "day-07-04" | "day-07-05" | "day-07-06" | "day-07-07" | "day-08-01" | "day-08-02" | "day-08-03" | "day-08-04" | "day-08-05" | "day-08-06" | "day-08-07" | "day-08-08";

export interface TeamDiaryImageAsset {
  readonly full: StaticImageData;
  readonly thumbnail: StaticImageData;
}

export const teamDiaryImageAssets = {
  "day-01-01": { full: teamDiaryAsset01Full, thumbnail: teamDiaryAsset01Thumbnail },
  "day-01-02": { full: teamDiaryAsset02Full, thumbnail: teamDiaryAsset02Thumbnail },
  "day-01-03": { full: teamDiaryAsset03Full, thumbnail: teamDiaryAsset03Thumbnail },
  "day-01-04": { full: teamDiaryAsset04Full, thumbnail: teamDiaryAsset04Thumbnail },
  "day-01-05": { full: teamDiaryAsset05Full, thumbnail: teamDiaryAsset05Thumbnail },
  "day-01-06": { full: teamDiaryAsset06Full, thumbnail: teamDiaryAsset06Thumbnail },
  "day-01-07": { full: teamDiaryAsset07Full, thumbnail: teamDiaryAsset07Thumbnail },
  "day-01-08": { full: teamDiaryAsset08Full, thumbnail: teamDiaryAsset08Thumbnail },
  "day-01-09": { full: teamDiaryAsset09Full, thumbnail: teamDiaryAsset09Thumbnail },
  "day-02-01": { full: teamDiaryAsset10Full, thumbnail: teamDiaryAsset10Thumbnail },
  "day-02-02": { full: teamDiaryAsset11Full, thumbnail: teamDiaryAsset11Thumbnail },
  "day-02-03": { full: teamDiaryAsset12Full, thumbnail: teamDiaryAsset12Thumbnail },
  "day-02-04": { full: teamDiaryAsset13Full, thumbnail: teamDiaryAsset13Thumbnail },
  "day-02-05": { full: teamDiaryAsset14Full, thumbnail: teamDiaryAsset14Thumbnail },
  "day-02-06": { full: teamDiaryAsset15Full, thumbnail: teamDiaryAsset15Thumbnail },
  "day-02-07": { full: teamDiaryAsset16Full, thumbnail: teamDiaryAsset16Thumbnail },
  "day-02-08": { full: teamDiaryAsset17Full, thumbnail: teamDiaryAsset17Thumbnail },
  "day-03-01": { full: teamDiaryAsset18Full, thumbnail: teamDiaryAsset18Thumbnail },
  "day-03-02": { full: teamDiaryAsset19Full, thumbnail: teamDiaryAsset19Thumbnail },
  "day-03-03": { full: teamDiaryAsset20Full, thumbnail: teamDiaryAsset20Thumbnail },
  "day-03-04": { full: teamDiaryAsset21Full, thumbnail: teamDiaryAsset21Thumbnail },
  "day-03-05": { full: teamDiaryAsset22Full, thumbnail: teamDiaryAsset22Thumbnail },
  "day-03-06": { full: teamDiaryAsset23Full, thumbnail: teamDiaryAsset23Thumbnail },
  "day-03-07": { full: teamDiaryAsset24Full, thumbnail: teamDiaryAsset24Thumbnail },
  "day-03-08": { full: teamDiaryAsset25Full, thumbnail: teamDiaryAsset25Thumbnail },
  "day-03-09": { full: teamDiaryAsset26Full, thumbnail: teamDiaryAsset26Thumbnail },
  "day-03-10": { full: teamDiaryAsset27Full, thumbnail: teamDiaryAsset27Thumbnail },
  "day-04-01": { full: teamDiaryAsset28Full, thumbnail: teamDiaryAsset28Thumbnail },
  "day-04-02": { full: teamDiaryAsset29Full, thumbnail: teamDiaryAsset29Thumbnail },
  "day-04-03": { full: teamDiaryAsset30Full, thumbnail: teamDiaryAsset30Thumbnail },
  "day-04-04": { full: teamDiaryAsset31Full, thumbnail: teamDiaryAsset31Thumbnail },
  "day-04-05": { full: teamDiaryAsset32Full, thumbnail: teamDiaryAsset32Thumbnail },
  "day-04-06": { full: teamDiaryAsset33Full, thumbnail: teamDiaryAsset33Thumbnail },
  "day-04-07": { full: teamDiaryAsset34Full, thumbnail: teamDiaryAsset34Thumbnail },
  "day-04-08": { full: teamDiaryAsset35Full, thumbnail: teamDiaryAsset35Thumbnail },
  "day-04-09": { full: teamDiaryAsset36Full, thumbnail: teamDiaryAsset36Thumbnail },
  "day-05-01": { full: teamDiaryAsset37Full, thumbnail: teamDiaryAsset37Thumbnail },
  "day-05-02": { full: teamDiaryAsset38Full, thumbnail: teamDiaryAsset38Thumbnail },
  "day-05-03": { full: teamDiaryAsset39Full, thumbnail: teamDiaryAsset39Thumbnail },
  "day-05-04": { full: teamDiaryAsset40Full, thumbnail: teamDiaryAsset40Thumbnail },
  "day-05-05": { full: teamDiaryAsset41Full, thumbnail: teamDiaryAsset41Thumbnail },
  "day-05-06": { full: teamDiaryAsset42Full, thumbnail: teamDiaryAsset42Thumbnail },
  "day-05-07": { full: teamDiaryAsset43Full, thumbnail: teamDiaryAsset43Thumbnail },
  "day-05-08": { full: teamDiaryAsset44Full, thumbnail: teamDiaryAsset44Thumbnail },
  "day-05-09": { full: teamDiaryAsset45Full, thumbnail: teamDiaryAsset45Thumbnail },
  "day-05-10": { full: teamDiaryAsset46Full, thumbnail: teamDiaryAsset46Thumbnail },
  "day-05-11": { full: teamDiaryAsset47Full, thumbnail: teamDiaryAsset47Thumbnail },
  "day-06-01": { full: teamDiaryAsset48Full, thumbnail: teamDiaryAsset48Thumbnail },
  "day-06-02": { full: teamDiaryAsset49Full, thumbnail: teamDiaryAsset49Thumbnail },
  "day-06-03": { full: teamDiaryAsset50Full, thumbnail: teamDiaryAsset50Thumbnail },
  "day-06-04": { full: teamDiaryAsset51Full, thumbnail: teamDiaryAsset51Thumbnail },
  "day-06-05": { full: teamDiaryAsset52Full, thumbnail: teamDiaryAsset52Thumbnail },
  "day-06-06": { full: teamDiaryAsset53Full, thumbnail: teamDiaryAsset53Thumbnail },
  "day-06-07": { full: teamDiaryAsset54Full, thumbnail: teamDiaryAsset54Thumbnail },
  "day-06-08": { full: teamDiaryAsset55Full, thumbnail: teamDiaryAsset55Thumbnail },
  "day-07-01": { full: teamDiaryAsset56Full, thumbnail: teamDiaryAsset56Thumbnail },
  "day-07-02": { full: teamDiaryAsset57Full, thumbnail: teamDiaryAsset57Thumbnail },
  "day-07-03": { full: teamDiaryAsset58Full, thumbnail: teamDiaryAsset58Thumbnail },
  "day-07-04": { full: teamDiaryAsset59Full, thumbnail: teamDiaryAsset59Thumbnail },
  "day-07-05": { full: teamDiaryAsset60Full, thumbnail: teamDiaryAsset60Thumbnail },
  "day-07-06": { full: teamDiaryAsset61Full, thumbnail: teamDiaryAsset61Thumbnail },
  "day-07-07": { full: teamDiaryAsset62Full, thumbnail: teamDiaryAsset62Thumbnail },
  "day-08-01": { full: teamDiaryAsset63Full, thumbnail: teamDiaryAsset63Thumbnail },
  "day-08-02": { full: teamDiaryAsset64Full, thumbnail: teamDiaryAsset64Thumbnail },
  "day-08-03": { full: teamDiaryAsset65Full, thumbnail: teamDiaryAsset65Thumbnail },
  "day-08-04": { full: teamDiaryAsset66Full, thumbnail: teamDiaryAsset66Thumbnail },
  "day-08-05": { full: teamDiaryAsset67Full, thumbnail: teamDiaryAsset67Thumbnail },
  "day-08-06": { full: teamDiaryAsset68Full, thumbnail: teamDiaryAsset68Thumbnail },
  "day-08-07": { full: teamDiaryAsset69Full, thumbnail: teamDiaryAsset69Thumbnail },
  "day-08-08": { full: teamDiaryAsset70Full, thumbnail: teamDiaryAsset70Thumbnail },
} as const satisfies Record<TeamDiaryImageId, TeamDiaryImageAsset>;
